package com.fraud_detector.project.dto.request;

import com.fraud_detector.project.enums.Channel;
import com.fraud_detector.project.enums.PaymentMethod;

import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Positive;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Input payload of POST /transaction.
 *
 * IMPORTANT (see AGENTS.md and the add-transaction-event skill): this API
 * NEVER evaluates whether any of these fields indicates fraud — it only
 * validates the format/presence of the data and publishes everything to SQS.
 * All risk analysis (including which of these fields actually matter for
 * each rule) is the sole responsibility of the fraud-detector-lambda.
 *
 * The fields beyond the four "essential" ones (userId, amount, currency,
 * merchant) exist to give the Lambda common real-world fraud signals, even
 * if no rule uses them yet — the idea is to avoid a cross-repo (API +
 * Lambda) change just to start using data that could already be available
 * from the start.
 */
public record TransactionRequestDTO(

        @NotBlank(message = "userId is required")
        String userId,

        @NotNull(message = "amount is required")
        @Positive(message = "amount must be positive")
        @DecimalMax(value = "1000000.00", message = "amount exceeds the maximum allowed value")
        BigDecimal amount,

        @NotBlank(message = "currency is required")
        @Pattern(regexp = "[A-Z]{3}", message = "currency must be a 3-letter ISO 4217 code (e.g. USD, BRL, EUR)")
        String currency,

        @NotBlank(message = "merchant is required")
        String merchant,

        // Merchant category (free text or MCC code). Risk signal: certain
        // categories (gambling, crypto exchange) historically have a higher
        // fraud rate.
        String merchantCategory,

        @NotNull(message = "paymentMethod is required")
        PaymentMethod paymentMethod,

        // Only relevant when paymentMethod is CREDIT_CARD/DEBIT_CARD.
        // There is no cross-field "required if card" validation here on
        // purpose — the API must not carry conditional business rules; it
        // only validates the format when the field is provided.
        @Pattern(regexp = "\\d{4}", message = "cardLastFourDigits must be exactly 4 digits")
        String cardLastFourDigits,

        @NotNull(message = "channel is required")
        Channel channel,

        // Simple IPv4. Risk signal: IP geolocation diverging from the
        // billing country, or an IP associated with a known VPN/proxy.
        @Pattern(
                regexp = "^(\\d{1,3}\\.){3}\\d{1,3}$",
                message = "ipAddress must be a valid IPv4 address"
        )
        String ipAddress,

        // Device identifier (fingerprint generated by the client). Risk
        // signal: same device used by multiple users, or a new device
        // never seen for this user.
        String deviceId,

        // Transaction geolocation (if the client/app provides it). Classic
        // risk signal: "impossible travel" — two transactions from the
        // same user in locations physically incompatible with the time
        // elapsed between them.
        @DecimalMin(value = "-90.0", message = "latitude must be between -90 and 90")
        @DecimalMax(value = "90.0", message = "latitude must be between -90 and 90")
        Double latitude,

        @DecimalMin(value = "-180.0", message = "longitude must be between -180 and 180")
        @DecimalMax(value = "180.0", message = "longitude must be between -180 and 180")
        Double longitude,

        // User's billing country (ISO 3166-1 alpha-2, e.g. "BR", "US").
        // Compared with geolocation/IP to detect divergence.
        @Pattern(regexp = "[A-Z]{2}", message = "billingCountry must be a 2-letter ISO 3166-1 country code")
        String billingCountry,

        @NotNull(message = "occurredAt is required")
        Instant occurredAt

) {}
