spring:
  application:
    name: fraud-detector
  profiles:
    active: dev

aws:
  region: ${AWS_REGION:us-east-1}
  access-key-id: ${AWS_ACCESS_KEY_ID:}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
  sqs:
    endpoint: ${AWS_SQS_ENDPOINT:}
    queue-name: ${AWS_SQS_QUEUE_NAME:}
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:}
    users-table: ${AWS_DYNAMODB_USERS_TABLE:users}
    transactions-table: ${AWS_DYNAMODB_TRANSACTIONS_TABLE:transactions}
  lambda:
    endpoint: ${AWS_LAMBDA_ENDPOINT:}
    function-name: ${AWS_LAMBDA_FUNCTION_NAME:fraud-detector-analysis-dev}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /docs
