spring:
  application:
    name: fraud-detector-prod

aws:
  region: ${AWS_REGION}
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  sqs:
    endpoint: ${SQS_ENDPOINT}
    queue-name: fraud-detector-transaction-queue-prod
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT}
    users-table: fraud-detector-users-prod
    transactions-table: fraud-detector-transactions-prod

logging:
  level:
    com.fraud_detector.project: INFO
